export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_ERROR = 'FETCH_PLACES_ERROR';

export default {
  FETCH_PLACES,
  FETCH_PLACES_SUCCESS,
  FETCH_PLACES_ERROR,
}