export const FETCH_ENTITY = 'FETCH_ENTITY';
export const FETCH_ENTITY_SUCCESS = 'FETCH_ENTITY_SUCCESS';
export const FETCH_ENTITY_ERROR = 'FETCH_ENTITY_ERROR';

export default {
  FETCH_ENTITY,
  FETCH_ENTITY_SUCCESS,
  FETCH_ENTITY_ERROR,
}